from kyaml import KYAML
from pkgMng import *
from prompt import *
from writer import *
from os import mkdir


class Constructor:
  """ Holds functions for generating a project. """

  def __init__(self, _lib: DiscordLibrary) -> None: self.lib, self.prompt = _lib, Prompt()

  def gen_project(self) -> None:
    match self.lib:
      case DiscordLibrary.DISCORD_JS: self.__gen_djs_project()
      case DiscordLibrary.DISCORD_PY: self.__gen_dpy_project()
      case DiscordLibrary.JDA: self.__gen_jda_project()
      case DiscordLibrary.PYCORD: self.__gen_pycord_project()
      case _: raise KrappyError("unknown library", 1)

  def __gen_djs_project(self) -> None:
    pm = self.prompt.get_js_package_manager()
    install_cmd = ''

    match pm:
      case JSPackageManager.NPM: install_cmd = "npm i"
      case JSPackageManager.PNPM: install_cmd = "pnpm i"  # Need to double check.
      case JSPackageManager.YARN: install_cmd = "yarn add"
      case JSPackageManager.BUN: install_cmd = "bun add"

    options = self.prompt.get_djs_options()
    options |= self.prompt.get_general_options()
    options |= self.prompt.get_path(str(options["name"]))
    options |= self.prompt.get_token()

    path = str(options["path"]).replace('\\', '/')  # Windows moment...
    lang = str(options["language"])

    # `krappy.yaml`.
    krappy_yaml = SourceCode(f"""# Generated by Krappy, do not edit!\n
options:
  language: {options["language"]}
  module_type: {options["module_type"]}
  name: {options["name"]}
  globalcmds: {options["globalcmds"]}
  path: {path}
  pmi: {install_cmd}
""", "%s/krappy.yaml" %path)
    Writer.write_src(krappy_yaml)

    # `.env`.
    dotenv_code = SourceCode(f"""TOKEN={options["token"]}
CLIENT_ID={options["clientid"]}
{f"GUILD_ID={options["guildid"]}" if "guildid" in options else ''}
""", "%s/.env" %path)
    Writer.write_src(dotenv_code)

    # `package.json`.
    pkg_json = SourceCode(f"""{{
  "name": "{options["name"]}",
  "version": "1.0.0",
  "description": "Generated with Krappy :)",
  "main": "src/index.{lang}",
  "scripts": {{
    "test": "echo \\"Error: no test specified\\" && exit 1"
  }},
  "keywords": [],
  "author": "",
  "license": "ISC"
}}
""", "%s/package.json" %path)
    Writer.write_src(pkg_json)

    # Make directories.
    mkdir("%s/src" %path)
    mkdir("%s/src/commands" %path)
    mkdir("%s/src/commands/misc" %path)
    mkdir("%s/src/events" %path)

    Writer.touch(f"{path}/src/index.{lang}")
    Writer.touch(f"{path}/src/commands/misc/ping.{lang}")
    Writer.touch(f"{path}/src/events/ready.{lang}")
    Writer.touch(f"{path}/src/events/interactionCreate.{lang}")

    if lang == "ts":  # TypeScript (🔥)
      Writer.touch(f"{path}/src/bot.ts")

    else:  # JavaScript (🗑️)
      ...

    # Install packages and conclude.
    PkgMng(install_cmd, "discord.js", "glob", "dotenv" if not pm == JSPackageManager.BUN else None).install()
    self.conclude(path)

  def conclude(self, _path: str) -> None: return print("Successfully generated in %s!" %_path)

  def __gen_dpy_project(self) -> None: ...
  def __gen_jda_project(self) -> None: ...
  def __gen_pycord_project(self) -> None: ...
