from prompt import DiscordLibrary, Prompt


if __name__ == "__main__":
    try:
        lib = Prompt.get_library()

        match lib:
            case DiscordLibrary.DISCORD_JS: ...
            case DiscordLibrary.DISCORD_PY: ...
            case DiscordLibrary.JDA: ...
            case DiscordLibrary.PYCORD: ...
            case _: raise

    except KeyboardInterrupt: ...
